### ISSUE TITLE
New version: 2.8.0.0

### ISSUE THREAD

**Issue by maxice8** [CMB/skaware-void-sysdeps#8]

**Comment by CMB** [comment]
Sorry, I'll try and get this tested and uploaded in the next day or so.

**Comment by maxice8** [comment]
On Tue, Mar 05, 2019 at 06:22:09PM -0800, Chris Brannon wrote:
> Sorry, I'll try and get this tested and uploaded in the next day or so.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/CMB/skaware-void-sysdeps/issues/8#issuecomment-469940653

No need to hurry, thanks for your work.

**Comment by CMB** [comment]
Pushed the new sysdeps this morning.
Good luck!
